Repository revaturelabs/trackforce, pull requests merged in 2018-08, with the labels that each got.

#632 Updated Angular to be on one version
  NGTrackForce/package.json
Labels: enhancement

#716 Output alert success message
  NGTrackForce/src/app/components/associate-list/associate-list.component.ts
  NGTrackForce/src/app/components/myinterview-view/myinterview-view.component.html
  NGTrackForce/src/app/components/myinterview-view/myinterview-view.component.ts
  NGTrackForce/src/app/components/navbar/navbar.component.ts
Labels: Client - Associate User, client, enhancement

#746 Associate Service Update
  NGTrackForce/src/app/components/associate-list/associate-list.component.ts
  NGTrackForce/src/app/components/form-component/form.component.ts
  NGTrackForce/src/app/components/home/home.component.ts
  NGTrackForce/src/app/services/associate-service/associate.service.ts
Labels: Client - Admin User, Client - Associate User, Client - Delivery/Sales, Client - Staging Manager, Client - Trainer User, client, enhancement

#741 Associate with ID 0 is now loaded in associate list
  NGTrackForce/src/app/components/associate-list/associate-list.component.html
  NGTrackForce/src/app/components/deployed/deployed.component.html
  NGTrackForce/src/app/components/form-component/form.component.html
Labels: client

#757 Fix for merge conflict that got pushed
  NGTrackForce/src/app/components/associate-list/associate-list.component.html
Labels: client

#751 Trainer update fix
  NGTrackForce/src/app/components/trainer-view/trainer-view.component.css
  NGTrackForce/src/app/components/trainer-view/trainer-view.component.html
  NGTrackForce/src/app/components/trainer-view/trainer-view.component.ts
  NGTrackForce/src/app/services/trainer-service/trainer.service.ts
  TrackForce/src/main/java/com/revature/resources/TrainerResource.java
Labels: client

#739 Added message to indicate approval success
  NGTrackForce/src/app/components/form-component/form.component.html
  NGTrackForce/src/app/components/form-component/form.component.ts
  NGTrackForce/src/app/services/interview-service/interview.service.ts
Labels: client
