Repository revaturelabs/trackforce, pull requests merged in 2018-09, with the labels that each got.

#779 Admin create user
  NGTrackForce/src/app/components/create-user/create-user.component.html
  NGTrackForce/src/app/components/create-user/create-user.component.ts
  NGTrackForce/src/app/components/create-user/create-user.enum.ts
  NGTrackForce/src/app/services/user-service/user.service.ts
  TrackForce/src/main/java/com/revature/entity/TfAssociate.java
Labels: client

#768 Prediction tab year restriction
  NGTrackForce/src/app/components/datetimepicker/datetimepicker.component.ts
  NGTrackForce/src/app/components/predictions/predictions.component.html
  NGTrackForce/src/app/components/predictions/predictions.component.ts
Labels: client

#805 Observable of Update
  NGTrackForce/src/app/components/associate-view/associate-view.component.spec.ts
Labels: Test, bug

#815 A merge conflict was pushed
  NGTrackForce/src/app/components/deployed/deployed.component.html
Labels: bug

#817 Added Compodoc
  NGTrackForce/package.json
Labels: enhancement

#802 UI and bug update on interview-details component
  NGTrackForce/src/app/components/interview-details/interview-details.component.html
  NGTrackForce/src/app/components/interview-details/interview-details.component.ts
  NGTrackForce/src/app/components/interview-details/interview-details.enum.ts
  NGTrackForce/src/app/services/interview-service/interview.service.ts
Labels: client

#827 Batch-List, Batch-Detail, Client-List, Create-User, TrainerView UI
  NGTrackForce/src/app/components/associate-view/associate-view.component.css
  NGTrackForce/src/app/components/associate-view/associate-view.component.html
  NGTrackForce/src/app/components/batch-details/batch-details.component.css
  NGTrackForce/src/app/components/batch-details/batch-details.component.html
  NGTrackForce/src/app/components/batch-list/batch-list.component.css
  NGTrackForce/src/app/components/batch-list/batch-list.component.html
  NGTrackForce/src/app/components/batch-list/batch-list.component.ts
  NGTrackForce/src/app/components/client-list/client-list.component.css
  NGTrackForce/src/app/components/client-list/client-list.component.html
  NGTrackForce/src/app/components/create-user/create-user.component.css
  NGTrackForce/src/app/components/create-user/create-user.component.html
  NGTrackForce/src/app/components/create-user/create-user.enum.ts
  NGTrackForce/src/app/components/trainer-view/trainer-view.component.css
  NGTrackForce/src/app/components/trainer-view/trainer-view.component.html
Labels: client

#843 Prediction UI
  NGTrackForce/src/app/components/batch-list/batch-list.component.html
  NGTrackForce/src/app/components/home/home.component.css
  NGTrackForce/src/app/components/home/home.component.html
  NGTrackForce/src/app/components/predictions/predictions.component.css
  NGTrackForce/src/app/components/predictions/predictions.component.html
Labels: client

#842 New salesforce changes made 9/11
  NGTrackForce/src/app/components/salesforce/salesforce.component.css
  NGTrackForce/src/app/components/salesforce/salesforce.component.html
Labels: client

#841 Navbar changes 9/11
  NGTrackForce/src/app/components/navbar/navbar.component.html
Labels: client

#801 Associate update
  NGTrackForce/src/app/components/associate-view/associate-view.component.css
  NGTrackForce/src/app/components/associate-view/associate-view.component.html
  NGTrackForce/src/app/components/associate-view/associate-view.component.ts
  NGTrackForce/src/app/components/associate-view/associate-view.enum.ts
  NGTrackForce/src/app/components/myinterview-view/myinterview-view.component.css
  NGTrackForce/src/app/components/myinterview-view/myinterview-view.component.html
  NGTrackForce/src/app/components/myinterview-view/myinterview-view.component.ts
  NGTrackForce/src/app/components/myinterview-view/myinterview-view.enum.ts
  NGTrackForce/src/app/models/interview.model.ts
Labels: client

#867 Pagenation
  NGTrackForce/src/app/app.module.ts
  NGTrackForce/src/app/components/associate-list-page/associate-list-page.component.css
  NGTrackForce/src/app/components/associate-list-page/associate-list-page.component.html
  NGTrackForce/src/app/components/associate-list-page/associate-list-page.component.spec.ts
  NGTrackForce/src/app/components/associate-list-page/associate-list-page.component.ts
  NGTrackForce/src/app/components/associate-list-page/update-dialog-component.html
  NGTrackForce/src/app/components/associate-list/associate-list.component.css
  NGTrackForce/src/app/components/associate-list/associate-list.component.html
  NGTrackForce/src/app/components/associate-list/associate-list.component.spec.ts
  NGTrackForce/src/app/components/associate-list/associate-list.component.ts
  NGTrackForce/src/app/components/associate-list/associate-list.enum.ts
  NGTrackForce/src/app/components/navbar/navbar.component.html
  NGTrackForce/src/app/constants/selected-status.constants.ts
  NGTrackForce/src/app/routing/routes.ts
  NGTrackForce/src/app/services/associate-service/associate.service.ts
  NGTrackForce/src/app/services/client-service/client.service.ts
  NGTrackForce/src/styles.css
Labels: client, enhancement
